# Config file for PhantomX Reactor
port: /dev/ttyUSB_REACTOR
rate: 50
joints: {
    arm_1_joint: {id: 1, max_speed: 75.0},
    arm_2_joint: {id: 2, max_speed: 75.0},
    arm_2_1_joint: {id: 3, max_speed: 75.0},
    arm_3_joint: {id: 4, max_speed: 75.0},
    arm_3_1_joint: {id: 5, max_speed: 75.0},
    arm_4_joint: {id: 6, max_speed: 75.0},
    arm_gripper_joint: {id: 8, max_speed: 125.0, range: 180, min_angle: -90.0, max_angle: 0},
}

# incrase read/write freq to prevent arm shaking.
read_rate: 50.0
write_rate: 50.0
